# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 05:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170217_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(90.0), django.core.validators.MinValueValidator(-90.0)]),
        ),
        migrations.AlterField(
            model_name='trail',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(180.0), django.core.validators.MinValueValidator(-180.0)]),
        ),
    ]
