# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170217_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trail_images/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Trail')),
            ],
        ),
    ]
